### ISSUE TITLE
UI: detect coins amount in level at runtime

### ISSUE THREAD

**Issue by davcri** [crystal-bit/platform-3d#6]

**Comment by lucashilles** [comment]
I implemented global state in the game to track scores, but a question arose, should coins inside boxes also be counted?

**Comment by lucashilles** [comment]
If we do not include them in the total count, the player may be led to believe that he has found a secret in the game, on the other hand, a score of 15/13 may look like a bug.

I have mixed feelings about the options, but I'm thinking about adding them to the total count.

**Comment by lucashilles** [comment]
I updated the PR to count crate coins and split the changes into more commits
